Fix failing multi-GPU CI: Move input tokens to device (#795)
## Describe your changes

Failing multi-GPU CI test, introduced in #769 but Oskar could not repro in a devbox:
```
___________________ test_doesnt_crash_autoregressive_gen_gcg ___________________
...
tests/test_autoregressive_gen_attacks_dont_crash.py:78: in _test_doesnt_crash
    run_evaluation_pipeline(config)
robust_llm/pipelines/evaluation_pipeline.py:83: in run_evaluation_pipeline
    results = do_adversarial_evaluation(
robust_llm/evaluation.py:85: in do_adversarial_evaluation
    attack_out = attack.get_attacked_dataset(
robust_llm/attacks/search_based/search_based.py:128: in get_attacked_dataset
    final_attack_string, example_info = runner.run()
robust_llm/attacks/search_based/runners/search_based_runner.py:86: in run
    self._get_candidate_texts_and_replacements(cand_texts)
robust_llm/attacks/search_based/runners/gcg_runner.py:64: in _get_candidate_texts_and_replacements
    gradients = self._compute_gradients(attack_text)
robust_llm/attacks/search_based/runners/gcg_runner.py:93: in _compute_gradients
    cb_out = self.differentiable_embeds_callback(self.victim, cb_in)
robust_llm/scoring_callbacks/scoring_callbacks.py:152: in losses_from_embeds_callback
    losses = _generation_losses_from_embeds(
robust_llm/scoring_callbacks/scoring_callback_utils.py:444: in _generation_losses_from_embeds
    for out in output_generator:
robust_llm/models/wrapped_model.py:595: in generation_output_from_embeddings
    out = self(
robust_llm/models/caching_wrapped_model.py:44: in __call__
    return self.forward(**inputs)
robust_llm/models/caching_wrapped_model.py:76: in forward                                                                                                                                                                                                                                                                                                                     input_ids = self.accelerator.gather_for_metrics(input_ids)                                                                                                                                                                                                                                                                                                            

...

ValueError: Tensors must be CUDA and dense
```

This reproduced fine for me on a devbox, not sure what was different in Oskar's setup. The `input_ids` are on `cpu` here, so we just need to move them on to the model's device somewhere. PR #769 introduced the failure by `gather`ing , which only works on GPU when using NCCL. `input_ids` has always been on `cpu`, but I think this wasn't an issue previously because `wrapped_model.forward()` explicitly moves the inputs to the model's device just in case. 

This PR moves `input_ids` to the model's device in the earliest place possible: where the IDs are generated in `SearchBasedRunner::_get_tokens`.

## Issue ticket number and link

PR #791

## Describe tests performed

CI is green again

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a new feature, I have added thorough tests.
- [ ] I have considered how it would affect the multi-GPU case and tested on a multi-GPU node if appropriate.
- [ ] If it is a high-risk change, I have run the following experiments to verify that the results are as expected:
    - [ ] [experiment=ian/027_eval_refactored_random_token_imdb model.name_or_path=AlignmentResearch/robust_llm_pythia-imdb-1.4b-mz-ada-v3](https://wandb.ai/farai/robust-llm/runs/zlynwimq)
    - [ ] [experiment=ian/028_eval_refactored_gcg_imdb model.name_or_path=AlignmentResearch/robust_llm_pythia-imdb-2.8b-mz-ada-v3](https://wandb.ai/farai/robust-llm/runs/pi6eq0wp)
    - [ ] [experiment=niki/1_DEBUG_niki_128](https://wandb.ai/farai/robust-llm/runs/76h9beb3)